config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about'

  resources :books, only: [:create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:index, :show, :edit ,:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum:200 }

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image
  validates :name, presence: true, uniqueness: true, length:{ in: 2..20 }
  validates :introduction, length: { maximum:50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!, except: [:top, :about]
 before_action :configure_permitted_parameters, if: :devise_controller?

 def after_sign_in_path_for(resource)
   user_path(current_user)
   # ログイン直後はユーザーの詳細ページへ遷移
 end

 def after_sign_out_path_for(resource)
   root_path

 end


 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
 end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
  if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
  else
    @books = Book.all
    @user = current_user
    render :index
  end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new

  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @users = current_user
    @new_book = Book.new
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path

  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @user = current_user
    @book = Book.find(params[:id])
  if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
  else
    render :edit
  end
  end

  #投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless current_user.id == book.user.id
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def index
    @users= User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
  else
    render :edit
  end
  end

  #ユーザデータのストロングパラメータ
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)

  end

  def is_matching_login_user
    user= User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div>
  <%= flash[:notice] %>
</div>


  <% if new_book.errors.any? %>
    <h4><%= new_book.errors.count %>errors prohibited this obj from being saved:</h4><br>
    <ul>
      <% new_book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>


<div class="sidebar col-md-3 px-5 px-sm-0 mt-3">
  <!--ユーザーの情報-->
  <h2>User info</h2>
  <table class="table">
    <!--ユーザー情報-->
    <tr>
      <%= image_tag user.get_profile_image(100,100) %>
    </tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </table>
  <div class='row'>
    <a class="btn btn-outline-secondary btn-block" href="/users/<%= @user.id %>/edit">
        <i class="fa-solid fa-user-gear"></i>
    </a>
  </div>
  <!--投稿ページ-->
  <h2 class="mt-3">New book</h2>
<%= form_with model: new_book do |f| %>
 <h4>Title</h4>
 <%= f.text_field :title %>

 <h4>Opinion</h4>
 <%= f.text_area :body %><br>
 <%= f.submit 'Create Book', class: "btn btn-sm btn-success" %>
<% end %>

</div>

app/views/books/edit.html.erb
<div class='container '>
  <div class="row">
    <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mt-3 mx-auto">
      <h2>Editing Book</h2>
      <% if @book.errors.any? %>
        <h4><%= @book.errors.count %>error prohibited this obj from being saved:</h4>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
      <% end %>
      <%= form_with model: @book do |f| %>
        <div class="field">
          Title
           <%= f.text_field :title, autofocus: true, class: "form-control", placeholder:""%><br>
          Opinion
          <%=f.text_area :body, autofocus: true, class:"form-control", placeholder:"" %><br>
        </div>
        <div>
          <%= f.submit 'Update Book', class: "btn btn-sm btn-success" %>
        </div>
      <% end %>
      <div>
        <p><%= link_to "Show", book_path(@book) %>｜<%= link_to "Back", books_path %></p><br>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
  <!--ユーザ・投稿部分テンプレート設定-->
   <!--render 'list', new_book: @new_book, user: @user %>-->
<div>
  <%= flash[:notice] %>
</div>
<div class="container px-5 px-sm-0">
  <div>
    <% if @book.errors.any? %>
      <h4><%= @book.errors.count %>errors prohibited this obj from being saved:</h4><br>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row mt-3">
    <div class="col-md-3">
    <!--ユーザーの情報-->
      <h2>User info</h2>
      <table class="table">
        <!--ユーザー情報-->
        <tbody>
          <tr>
          <%= image_tag @user.get_profile_image(100,100) %>
          </tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <a class="btn btn-outline-secondary btn-block" href="/users/<%= @user.id %>/edit">
          <i class="fa-solid fa-user-gear"></i>
        </a>
      </div>
  <!--投稿ページ-->
      <h2 class="mt-3">New book</h2>
        <%= form_with model: @book do |f| %>
          <div class="field">
            <p>Title</p>
              <%= f.text_field :title, class: "form-control"  %><br>
            <p>Opinion</p>
              <%= f.text_area :body, class: "form-control" %><br>
            <%= f.submit 'Create Book', class: "btn btn-sm btn-success" %>
          </div>
        <% end %>
    </div>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <!--投稿ユーザー画像-->
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(80,80) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td> <%= book.body %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/books/show.html.erb
  <!--ユーザ・投稿部分テンプレート設定-->
  <!--render 'list', new_book: @new_book, user: @user %>-->
<div>
  <%= flash[:notice] %>
</div>
<div class="container px-5 px-sm-0">
  <div>
    <% if @new_book.errors.any? %>
      <h4><%= @new_book.errors.count %>errors prohibited this obj from being saved:</h4><br>
      <ul>
        <% @new_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row mt-3">
    <div class="col-md-3">
    <!--ユーザーの情報-->
      <h2>User info</h2>
      <table class="table">
        <!--ユーザー情報-->
        <tbody>
          <tr>
          <%= image_tag @user.get_profile_image(100,100) %>
          </tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <a class="btn btn-outline-secondary btn-block" href="/users/<%= @user.id %>/edit">
          <i class="fa-solid fa-user-gear"></i>
        </a>
      </div>
  <!--投稿ページ-->
      <h2 class="mt-3">New book</h2>
        <%= form_with model: @new_book do |f| %>
          <div class="field">
            Title
              <%= f.text_field :title, class: "form-control",placeholder:"" %><br>
            Opinion
              <%= f.text_area :body, class: "form-control", placeholder:"" %><br>
            <%= f.submit 'Create Book', class: "btn btn-sm btn-success" %>
          </div>
        <% end %>
    </div>
  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
      <table class="table">
      <!--ユーザー画像-->
      <tbody>
        <tr>
          <td><%= link_to user_path(@user) do %>
            <%= image_tag @user.get_profile_image(80,80) %><br>
            <%= @user.name %>
            <% end %>
          </td>
          <!--投稿タイトル-->
          <td>
            <%= link_to book_path(@book.id) do %>
            <%= @book.title %>
            <% end %>
          </td>
          <!--投稿内容-->
          <td>
            <%= @book.body %>
          </td>
          <% if @book.user == current_user %>
          <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
          <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？",class: "btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      </tbody>
      </table>
  </div>
</div>

app/views/homes/about.html.erb
<main>
  <div class="container mt-3">
    <div class="row">
    <div class="mx-auto">
      <h1>Welcome to
        <i class="fa-solid fa-book"></i>
        <strong>Bookers</strong>!
      </h1>
    </div>
    </div>
  </div>

 </main>

app/views/homes/top.html.erb
<div>
 <%= flash[:notice] %>
</div>
<div class="container mt-3">
 <div class="row">
  <div class ="col-11 col-sm-10 col-lg-8 col-xl-6 mx-auto">
   <h1>welcome to
    <i class="fa-solid fa-book"></i><strong>Bookers</strong>!!
   </h1>
   <p>In
    <i class="fa-solid fa-book"></i><strong>Bookers</strong>,
   </p>
   <p>
     you can share and exchange your opinions , inpressions , and emotions</br>
     about various books!
   </p>
   <div class="btn-wrapper col-10 mx-auto">
    <div class="row">
     <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
      <!--<p>link_to 'Log in', user_session_path, class: "sign-in", class: "btn btn-info" %></p>-->
    </div>
    <div class="row">
     <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
      <!--<p> link_to 'Sign up', new_user_registration_path, class: "sign-up", class: "btn btn-success" %></p>-->
    </div>
   </div>
  </div>
 </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>Bookers</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <!--Homeボタン-->
            <li>
              <a class ="nav-link text-light" href="/users/<%= current_user.id %>">
                <i class="fa-solid fa-house"></i>Home
              </a>
            </li>
            <!--<li class="nav-item">-->
               <!--link_to "Home", user_path(current_user.id), class: 'nav-link text-white'  %>-->
            <!--</li>-->
          <!--Usersボタン-->
            <li>
              <a class ="nav-link text-light" href="/users">
              <i class="fa-solid fa-users"></i>Users
              </a>
            </li>
            <!--<li class="nav-item">-->
               <!--link_to "Users", users_path, class: 'nav-link text-white' %>-->
            <!--</li>-->
          <!--Booksボタン-->
            <li>
              <a class="nav-link text-light" href="/books">
              <i class="fa-solid fa-book-open"></i>Books
              </a>
            </li>
            <!--<li class="nav-item">-->
               <!--link_to "Books", books_path, class: 'nav-link text-white' %>-->
            <!--</li>-->
          <!--Log outボタン-->
            <li>
              <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
                <i class="fa-solid fa-right-from-bracket"></i>Log out
              </a>
            </li>
            <!--<li class="nav-item">-->
               <!--link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>-->
            <!--</li>-->
          <% else %>
            <!--Homeボタン-->
            <li>
              <a class ="nav-link text-light" href="/">
                <i class="fa-solid fa-house"></i>Home
              </a>
            </li>
            <!--<li class="nav-item">-->
               <!--link_to "Home", root_path, class: 'nav-link text-white' %>-->
            <!--</li>-->
          <!--Aboutボタン-->
            <li>
              <a class ="nav-link text-light" href="/home/about">
                <i class="fa-solid fa-link"></i>About
              </a>
            </li>
            <!--<li class="nav-item">-->
               <!--link_to "About", about_path, class: 'nav-link text-white' %>-->
            <!--</li>-->
          <!--sign upボタン-->
            <li>
              <a class="nav-link text-light" href="/users/sign_up">
                <i class="fa-solid fa-user-plus"></i>Sign up
              </a>
            </li>
            <!--<li class="nav-item">-->
               <!--link_to "Sign up", new_user_registration_path, class: 'nav-link text-white' %>-->
            <!--</li>-->
          <!--Log_inボタン-->
            <li>
              <a class="nav-link text-light" href="/users/sign_in">
                <i class="fa-solid fa-right-to-bracket"></i>Log in
              </a>
            </li>
            <!--<li class="nav-item">-->
               <!--link_to "Log in", new_user_session_path, class: 'nav-link text-white' %>-->
            <!--</li>-->
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/0e58e38434.js" crossorigin="anonymous"></script>
      <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main class="mb-auto">
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/edit.html.erb
 <div class='container'>
  <div class="row">
   <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mt-3 mx-auto">
    <h2>User info</h2>
    <% if @user.errors.any? %>
      <h4><%= @user.errors.count %>error prohibited this obj from being saved:</h4>
      <ul>
       <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
       <% end %>
      </ul>
    <% end %>

    <%= form_with model: @user do |f| %>
      <div class="field">
        <p>Name</p>
        <%= f.text_field :name, autofocus: true, class: "form-control", placeholder:"" %><br>
        <p>ProfileImage</p>
        <%= f.file_field :profile_image, accept: "image/*" %><br>
        <p>Introduction</p>
        <%= f.text_area :introduction, autofocus: true, class:"form-control", placeholder:"" %><br>
      </div>
        <!--f.text_area :introduction, autofocus: true, id:"inputIntroduction",placeholder:"" %><br>-->
      <div class="form-group">
        <%= f.submit "Update User", class: "btn btn-md btn-secondary" %>
      </div>
    <% end %>
   </div>
  </div>
 </div>

app/views/users/index.html.erb
<!--ユーザ・投稿部分テンプレート設定-->
   <!--render 'books/list', new_book: @new_book, user: @user %>-->
<div>
  <%= flash[:notice] %>
</div>
<div class="container px-5 px-sm-0">
  <div>
    <% if @book.errors.any? %>
      <h4><%= @book.errors.count %>errors prohibited this obj from being saved:</h4><br>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row mt-3">
    <div class="col-md-3">
    <!--ユーザーの情報-->
      <h2>User info</h2>
      <table class="table">
        <tbody>
          <tr>
          <%= image_tag @user.get_profile_image(100,100) %>
          </tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <a class="btn btn-outline-secondary btn-block" href="/users/<%= @user.id %>/edit">
          <i class="fa-solid fa-user-gear"></i>
        </a>
      </div>
  <!--投稿ページ-->
      <h2 class="mt-3">New book</h2>
        <%= form_with model: @book do |f| %>
          <div class="field">
            Title
              <%= f.text_field :title, class: "form-control"  %><br>
            Opinion
              <%= f.text_area :body, class: "form-control" %><br>
            <%= f.submit 'Create Book', class: "btn btn-sm btn-success" %>
          </div>
            <% end %>
    </div>
    <div class="column col-md-8 offset-md-1">
      <h2>Users</h2>
        <!--ユーザー一覧-->
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th> </th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
          <!--プロフィール画像-->
            <td>
              <%= image_tag user.get_profile_image(100, 100) %>
            </td>
        　<!--ユーザー名-->
            <td>
              <%= user.name %>
            </td>
            <!--showページ(ユーザー)へのリンク-->
            <td>
              <%= link_to "Show", user_path(user) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!--ユーザ・投稿部分テンプレート設定-->
<div>
  <%= flash[:notice] %>
</div>
<div class="container px-5 px-sm-0">
  <div>
    <% if @book.errors.any? %>
      <h4><%= @book.errors.count %>errors prohibited this obj from being saved:</h4><br>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row mt-3">
    <div class="col-md-3">
    <!--ユーザーの情報-->
      <h2>User info</h2>
      <table class="table">
        <!--ユーザー情報-->
        <tbody>
          <tr>
          <%= image_tag @user.get_profile_image(100,100) %>
          </tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <a class="btn btn-outline-secondary btn-block" href="/users/<%= @user.id %>/edit">
          <i class="fa-solid fa-user-gear"></i>
        </a>
      </div>
  <!--投稿ページ-->
      <h2 class="mt-3">New book</h2>
        <%= form_with model: @book do |f| %>
          <div class="field">
            Title
              <%= f.text_field :title, class: "form-control"  %><br>
            Opinion
              <%= f.text_area :body, class: "form-control" %><br>
          </div>
          <div>
            <%= f.submit 'Create Book', class: "btn btn-sm btn-success" %>
          </div>
            <% end %>
    </div>
  <!--テーブルのレイアウト-->
  <!--ユーザーごとのBooks一覧-->
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <div>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(80,80) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td> <%= book.body %></td>
            </tr>
          </div>
        <% end %>
      </tbody>
    </table>
  </div>